### ISSUE TITLE
outdated part00.rs pointed to by `raw source` url on the online version

### ISSUE THREAD

**Issue by correabuscar** [RalfJung/rust-101#43]
Here: https://www.ralfj.de/projects/rust-101/part00.html
at the bottom, there's `raw source` url which is: https://www.ralfj.de/projects/rust-101/workspace/src/part00.rs
that's the contents of this file: https://github.com/RalfJung/rust-101/commit/229b86d07e94cd3ec175051a44b3f3cb45b40b65#diff-9b642a849800575121d05a3fee6d80f9cfc74c83cf393a3d02de40b4ee6479a7R28
which is outdated due to having many `unimplemented!()` lines compared to what the tutorial [url](https://www.ralfj.de/projects/rust-101/part00.html)[^1] code showed which had none.

[^1]: which seems to have been correctly generated from this up to date [file](https://github.com/RalfJung/rust-101/blob/63d67be4fd88cf041af103bd987a84397d5fe0f5/src/part00.rs#L114)

**Comment by RalfJung** [comment]
Thanks for the report!

This is deliberate, the point of the workspace is to provide a starting point for people that would participate in a course based on Rust-101, and a bunch of the code is removed there to encourage participants to type some code themselves rather than just using a template that is already complete.
